services:
  abacusflow-website:
    container_name: abacusflow-website
    image: ghcr.io/abacusflow/website:${ABACUSFLOW_WEBSITE_VERSION}
    environment:
      REDIRECT_TO_HTTPS: "false"
    networks:
      - abacusflow-network
    volumes:
      - /etc/letsencrypt/live/abacusflow.cn/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/abacusflow.cn/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "${ABACUSFLOW_WEBSITE_HTTP_PORT}:80"
      # - "${ABACUSFLOW_WEBSITE_HTTPS_PORT}:443"

networks:
  abacusflow-network:
    driver: bridge
    name: abacusflow-network