services:
  abacusflow-website:
    container_name: abacusflow-website
    image: ghcr.io/abacusflow/website:${ABACUSFLOW_WEBSITE_VERSION}
    restart: always
    environment:
      REDIRECT_TO_HTTPS: "false"
    volumes:
      - /etc/letsencrypt/output/abacusflow.cn/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/output/abacusflow.cn/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "${ABACUSFLOW_WEBSITE_HTTP_PORT}:80"
      # - "${ABACUSFLOW_WEBSITE_HTTPS_PORT}:443"
