services:
  abacusflow-website:
    container_name: abacusflow-website
    image: ghcr.io/abacusflow/website:${ABACUSFLOW_WEBSITE_VERSION}
    networks:
      - abacusflow-network
    volumes:
      - /opt/acme-https/www:/var/www/certbot:ro
      - /opt/acme-https/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"