# /etc/nginx/snippets/common_spa.conf
#
# 这个文件包含了所有 server 块共用的配置，
# 特别是针对单页应用 (SPA) 的设置。

# 网站文件的根目录
root /usr/share/nginx/html;
# 默认首页文件
index index.html;

# SPA 路由支持
# 对于任何未找到的文件或目录，都返回 index.html
location / {
    try_files $uri $uri/ /index.html;
}